version: "3"
services:
  db:
    image: mysql:8.0.13
    volumes:
      - person-volume:/var/lib/mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    networks:
      - person-network
    environment:
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: address
      MYSQL_USER: daming
      MYSQL_PASSWORD: 267552
volumes:
  person-volume:
    external: true
networks:
  person-network:
    external: true