version: "3"
services:
  person-db:
    image: mysql:8.0.13
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    networks:
      - person-network
    environment:
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: db_person
      MYSQL_USER: daming
      MYSQL_PASSWORD: 267552

networks:
  person-network:
    external: false