spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_person?serverTimezone=GMT%2B8
    username: root
    password: 267552
    driver-class-name: com.mysql.cj.jdbc.Driver

swagger:
  enabled: true

snowflake:
  workerId: 0
  datacenterId: 0

#url:
#  filter:
#    ignore: .*(swagger|webjars|configuration|token|images|api-docs).*
